/**
 * CompraNet Fallback Data
 *
 * Realistic licitaciones that mirror real CompraNet data format.
 * Used when the government API is unreachable or rate-limited.
 * All entity names, procedure numbers, and categories are realistic.
 */

import type { CompraNetLicitacion } from './client'

export const fallbackLicitaciones: CompraNetLicitacion[] = [
  {
    numero_procedimiento: 'LA-006000998-E35-2026',
    titulo: 'Servicio de infraestructura de computo en la nube (IaaS/PaaS/SaaS) para los sistemas institucionales del SAT',
    dependencia: 'Servicio de Administracion Tributaria',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-20T10:00:00Z',
    fecha_apertura: '2026-04-18T14:00:00Z',
    monto_estimado: 185_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2635001',
    categoria: 'Tecnologias de la Informacion',
    descripcion: 'Contratacion del servicio integral de infraestructura tecnologica en la nube para soportar los sistemas tributarios y aduaneros del SAT durante 36 meses, incluyendo migracion, operacion y soporte.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Administracion General de Comunicaciones y Tecnologias de la Informacion',
    numero_expediente: 'E35/2026',
    fecha_limite_aclaraciones: '2026-04-08T11:00:00Z',
  },
  {
    numero_procedimiento: 'LA-019GYR040-E12-2026',
    titulo: 'Adquisicion de medicamentos del cuadro basico y catalogo para unidades medicas del IMSS',
    dependencia: 'Instituto Mexicano del Seguro Social',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-18T08:00:00Z',
    fecha_apertura: '2026-04-22T10:00:00Z',
    monto_estimado: 2_350_000_000,
    estado: 'En periodo de aclaraciones',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2635102',
    categoria: 'Salud',
    descripcion: 'Adquisicion consolidada de medicamentos del cuadro basico y catalogo institucional para abastecer las unidades medicas de primero, segundo y tercer nivel del IMSS a nivel nacional.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Coordinacion de Adquisicion de Bienes y Contratacion de Servicios',
    numero_expediente: 'E12/2026',
    fecha_limite_aclaraciones: '2026-04-10T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-018TOQ001-E8-2026',
    titulo: 'Mantenimiento integral de la red de ductos de gas natural de la region Sur',
    dependencia: 'Petroleos Mexicanos',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-22T09:00:00Z',
    fecha_apertura: '2026-04-25T11:00:00Z',
    monto_estimado: 450_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2635203',
    categoria: 'Energia',
    descripcion: 'Servicio de mantenimiento preventivo, correctivo y predictivo de la red de ductos de transporte de gas natural en la region Sur-Sureste, incluyendo inspeccion con herramientas inteligentes.',
    entidad_federativa: 'Tabasco',
    unidad_compradora: 'Gerencia de Contrataciones para Transformacion Industrial',
    numero_expediente: 'E8/2026',
    fecha_limite_aclaraciones: '2026-04-14T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-006HHG001-E5-2026',
    titulo: 'Servicio de vigilancia y seguridad para inmuebles de la Comision Federal de Electricidad',
    dependencia: 'Comision Federal de Electricidad',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-25T10:00:00Z',
    fecha_apertura: '2026-04-28T14:00:00Z',
    monto_estimado: 320_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2635304',
    categoria: 'Seguridad',
    descripcion: 'Contratacion del servicio integral de vigilancia, proteccion y seguridad privada para los inmuebles y subestaciones de la CFE en la zona metropolitana y region centro del pais.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Gerencia de Abastecimientos',
    numero_expediente: 'E5/2026',
    fecha_limite_aclaraciones: '2026-04-16T11:00:00Z',
  },
  {
    numero_procedimiento: 'LA-051GYN001-E3-2026',
    titulo: 'Adquisicion de equipo medico especializado para hospitales del ISSSTE',
    dependencia: 'Instituto de Seguridad y Servicios Sociales de los Trabajadores del Estado',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-19T08:00:00Z',
    fecha_apertura: '2026-04-20T10:00:00Z',
    monto_estimado: 780_000_000,
    estado: 'Presentacion de propuestas',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2635405',
    categoria: 'Salud',
    descripcion: 'Adquisicion de equipo medico especializado incluyendo tomografos, resonancias magneticas, equipos de ultrasonido y laboratorio para hospitales regionales y de alta especialidad del ISSSTE.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Subdireccion de Infraestructura',
    numero_expediente: 'E3/2026',
    fecha_limite_aclaraciones: '2026-04-07T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-012000993-E21-2026',
    titulo: 'Servicio de limpieza integral para unidades administrativas de la Secretaria de Salud',
    dependencia: 'Secretaria de Salud',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-28T09:00:00Z',
    fecha_apertura: '2026-04-30T10:00:00Z',
    monto_estimado: 95_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2635506',
    categoria: 'Servicios Generales',
    descripcion: 'Servicio integral de limpieza para oficinas, laboratorios y areas comunes de las unidades administrativas centrales de la Secretaria de Salud en la Ciudad de Mexico.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Direccion General de Recursos Materiales y Servicios Generales',
    numero_expediente: 'E21/2026',
    fecha_limite_aclaraciones: '2026-04-18T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-011000001-E15-2026',
    titulo: 'Programa Nacional de Becas - sistema de gestion y pagos electronicos',
    dependencia: 'Secretaria de Educacion Publica',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-15T10:00:00Z',
    fecha_apertura: '2026-04-15T14:00:00Z',
    monto_estimado: 65_000_000,
    estado: 'En evaluacion',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2635607',
    categoria: 'Tecnologias de la Informacion',
    descripcion: 'Desarrollo e implementacion del sistema integral de gestion de becas y pagos electronicos para el Programa Nacional de Becas para el Bienestar Benito Juarez.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Direccion General de Tecnologias de la Informacion y Comunicaciones',
    numero_expediente: 'E15/2026',
    fecha_limite_aclaraciones: '2026-04-03T11:00:00Z',
  },
  {
    numero_procedimiento: 'LA-016B00001-E9-2026',
    titulo: 'Construccion de infraestructura hidraulica para el sistema Cutzamala',
    dependencia: 'Comision Nacional del Agua',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-10T08:00:00Z',
    fecha_apertura: '2026-04-12T10:00:00Z',
    monto_estimado: 1_200_000_000,
    estado: 'Adjudicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2635708',
    categoria: 'Obra Publica',
    descripcion: 'Construccion de infraestructura hidraulica complementaria para el Sistema Cutzamala, incluyendo planta potabilizadora, tanque de almacenamiento y linea de conduccion.',
    entidad_federativa: 'Estado de Mexico',
    unidad_compradora: 'Subdireccion General de Infraestructura Hidraulica',
    numero_expediente: 'E9/2026',
    fecha_limite_aclaraciones: '2026-03-28T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-009000002-E7-2026',
    titulo: 'Modernizacion de la autopista Mexico-Queretaro tramo km 60 a km 120',
    dependencia: 'Secretaria de Infraestructura, Comunicaciones y Transportes',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-12T09:00:00Z',
    fecha_apertura: '2026-04-14T11:00:00Z',
    monto_estimado: 3_500_000_000,
    estado: 'Adjudicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2635809',
    categoria: 'Obra Publica',
    descripcion: 'Modernizacion y ampliacion de la autopista Mexico-Queretaro en el tramo del km 60 al km 120, incluyendo tercer carril, puentes vehiculares y senalizacion inteligente.',
    entidad_federativa: 'Queretaro',
    unidad_compradora: 'Direccion General de Carreteras',
    numero_expediente: 'E7/2026',
    fecha_limite_aclaraciones: '2026-03-30T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-016000001-E18-2026',
    titulo: 'Servicio de monitoreo ambiental y analisis de calidad del aire en zonas metropolitanas',
    dependencia: 'Secretaria de Medio Ambiente y Recursos Naturales',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-26T10:00:00Z',
    fecha_apertura: '2026-04-26T10:00:00Z',
    monto_estimado: 42_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2635910',
    categoria: 'Medio Ambiente',
    descripcion: 'Servicio de monitoreo continuo de calidad del aire, medicion de contaminantes criterio y gases de efecto invernadero en las principales zonas metropolitanas del pais.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Direccion General de Gestion de la Calidad del Aire',
    numero_expediente: 'E18/2026',
    fecha_limite_aclaraciones: '2026-04-15T10:00:00Z',
  },
  {
    numero_procedimiento: 'IA-007000999-E2-2026',
    titulo: 'Adquisicion de uniformes y equipo tactico para personal militar',
    dependencia: 'Secretaria de la Defensa Nacional',
    tipo_procedimiento: 'Invitacion a cuando menos 3',
    fecha_publicacion: '2026-03-21T08:00:00Z',
    fecha_apertura: '2026-04-10T10:00:00Z',
    monto_estimado: 520_000_000,
    estado: 'En evaluacion',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2636011',
    categoria: 'Defensa',
    descripcion: 'Adquisicion de uniformes de campana, equipo tactico individual y equipo de proteccion balistico para el personal de tropa y oficiales de la SEDENA.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Direccion General de Administracion',
    numero_expediente: 'E2/2026',
    fecha_limite_aclaraciones: '2026-04-01T10:00:00Z',
  },
  {
    numero_procedimiento: 'IA-013000003-E4-2026',
    titulo: 'Mantenimiento de embarcaciones y equipo naval tipo patrulla interceptora',
    dependencia: 'Secretaria de Marina',
    tipo_procedimiento: 'Invitacion a cuando menos 3',
    fecha_publicacion: '2026-03-24T09:00:00Z',
    fecha_apertura: '2026-04-15T11:00:00Z',
    monto_estimado: 180_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2636112',
    categoria: 'Defensa',
    descripcion: 'Servicio de mantenimiento mayor, reparacion y modernizacion de embarcaciones tipo patrulla interceptora de 35 y 42 metros de eslora asignadas a zonas navales.',
    entidad_federativa: 'Veracruz',
    unidad_compradora: 'Direccion General de Recursos Materiales',
    numero_expediente: 'E4/2026',
    fecha_limite_aclaraciones: '2026-04-08T10:00:00Z',
  },
  {
    numero_procedimiento: 'AD-027000001-E6-2026',
    titulo: 'Consultoria para la implementacion del sistema de contrataciones abiertas',
    dependencia: 'Secretaria de la Funcion Publica',
    tipo_procedimiento: 'Adjudicacion Directa',
    fecha_publicacion: '2026-03-27T10:00:00Z',
    fecha_apertura: '2026-04-05T10:00:00Z',
    monto_estimado: 3_500_000,
    estado: 'Adjudicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2636213',
    categoria: 'Consultoria',
    descripcion: 'Servicio de consultoria especializada para la implementacion del Estandar de Datos de Contrataciones Abiertas (EDCA/OCDS) en los sistemas de CompraNet.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Unidad de Politica de Contrataciones Publicas',
    numero_expediente: 'E6/2026',
    fecha_limite_aclaraciones: '2026-04-02T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-019GYR040-E14-2026',
    titulo: 'Servicio de suministro de oxigeno medicinal y gases medicinales para unidades del IMSS',
    dependencia: 'Instituto Mexicano del Seguro Social',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-17T08:00:00Z',
    fecha_apertura: '2026-04-17T10:00:00Z',
    monto_estimado: 890_000_000,
    estado: 'Presentacion de propuestas',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2636314',
    categoria: 'Salud',
    descripcion: 'Suministro integral de oxigeno medicinal, aire medicinal, oxido nitroso y nitrogeno para hospitales generales de zona y unidades medicas de alta especialidad del IMSS.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Coordinacion de Adquisicion de Bienes y Contratacion de Servicios',
    numero_expediente: 'E14/2026',
    fecha_limite_aclaraciones: '2026-04-06T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-018TOQ001-E11-2026',
    titulo: 'Servicio de transporte maritimo de crudo tipo Maya y Olmeca',
    dependencia: 'Petroleos Mexicanos',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-14T09:00:00Z',
    fecha_apertura: '2026-04-16T11:00:00Z',
    monto_estimado: 4_200_000_000,
    estado: 'En evaluacion',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2636415',
    categoria: 'Energia',
    descripcion: 'Contratacion del servicio de fletamento de buques tanque para el transporte maritimo de petroleo crudo tipo Maya y Olmeca en rutas de cabotaje y altura.',
    entidad_federativa: 'Campeche',
    unidad_compradora: 'Gerencia de Contrataciones para Exploracion y Produccion',
    numero_expediente: 'E11/2026',
    fecha_limite_aclaraciones: '2026-04-04T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-006HHG001-E16-2026',
    titulo: 'Suministro de transformadores de potencia y distribucion para la red electrica nacional',
    dependencia: 'Comision Federal de Electricidad',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-23T10:00:00Z',
    fecha_apertura: '2026-04-24T14:00:00Z',
    monto_estimado: 1_800_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2636516',
    categoria: 'Energia',
    descripcion: 'Adquisicion de transformadores de potencia (115/230 kV) y transformadores de distribucion monofasicos y trifasicos para el programa de modernizacion de la red electrica nacional.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Gerencia de Abastecimientos',
    numero_expediente: 'E16/2026',
    fecha_limite_aclaraciones: '2026-04-12T11:00:00Z',
  },
  {
    numero_procedimiento: 'AD-006000998-E20-2026',
    titulo: 'Licenciamiento de software Microsoft Enterprise Agreement para el SAT',
    dependencia: 'Servicio de Administracion Tributaria',
    tipo_procedimiento: 'Adjudicacion Directa',
    fecha_publicacion: '2026-03-29T10:00:00Z',
    fecha_apertura: '2026-04-08T10:00:00Z',
    monto_estimado: 28_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2636617',
    categoria: 'Tecnologias de la Informacion',
    descripcion: 'Renovacion del licenciamiento Microsoft Enterprise Agreement incluyendo Office 365, Windows Server, SQL Server y Azure para todas las unidades administrativas del SAT.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Administracion General de Comunicaciones y Tecnologias de la Informacion',
    numero_expediente: 'E20/2026',
    fecha_limite_aclaraciones: '2026-04-04T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-050GYR001-E13-2026',
    titulo: 'Construccion del Hospital General de Zona No. 8 en Cancun, Quintana Roo',
    dependencia: 'Instituto Mexicano del Seguro Social',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-11T08:00:00Z',
    fecha_apertura: '2026-04-11T10:00:00Z',
    monto_estimado: 2_800_000_000,
    estado: 'Adjudicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2636718',
    categoria: 'Obra Publica',
    descripcion: 'Construccion integral del Hospital General de Zona No. 8 de 180 camas en Cancun, incluyendo obra civil, instalaciones, equipamiento y urbanizacion.',
    entidad_federativa: 'Quintana Roo',
    unidad_compradora: 'Division de Construccion y Planeacion Inmobiliaria',
    numero_expediente: 'E13/2026',
    fecha_limite_aclaraciones: '2026-03-28T10:00:00Z',
  },
  {
    numero_procedimiento: 'IA-012000993-E10-2026',
    titulo: 'Arrendamiento de vehiculos utilitarios para brigadas de vacunacion',
    dependencia: 'Secretaria de Salud',
    tipo_procedimiento: 'Invitacion a cuando menos 3',
    fecha_publicacion: '2026-03-26T09:00:00Z',
    fecha_apertura: '2026-04-13T10:00:00Z',
    monto_estimado: 56_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2636819',
    categoria: 'Salud',
    descripcion: 'Arrendamiento de vehiculos tipo pick-up y SUV con capacidad de refrigeracion para las brigadas del Programa Nacional de Vacunacion en los 32 estados.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Direccion General de Recursos Materiales y Servicios Generales',
    numero_expediente: 'E10/2026',
    fecha_limite_aclaraciones: '2026-04-05T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-006000998-E22-2026',
    titulo: 'Servicio administrado de centro de datos alterno para contingencias del SAT',
    dependencia: 'Servicio de Administracion Tributaria',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-30T10:00:00Z',
    fecha_apertura: '2026-04-30T14:00:00Z',
    monto_estimado: 75_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2636920',
    categoria: 'Tecnologias de la Informacion',
    descripcion: 'Servicio administrado de centro de datos alterno (DRP/BCP) para garantizar la continuidad operativa de los sistemas criticos del SAT ante contingencias.',
    entidad_federativa: 'Queretaro',
    unidad_compradora: 'Administracion General de Comunicaciones y Tecnologias de la Informacion',
    numero_expediente: 'E22/2026',
    fecha_limite_aclaraciones: '2026-04-18T11:00:00Z',
  },
  {
    numero_procedimiento: 'LA-009000002-E19-2026',
    titulo: 'Conservacion periodica de la carretera Transpeninsular en Baja California Sur',
    dependencia: 'Secretaria de Infraestructura, Comunicaciones y Transportes',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-20T09:00:00Z',
    fecha_apertura: '2026-04-21T11:00:00Z',
    monto_estimado: 280_000_000,
    estado: 'En periodo de aclaraciones',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2637021',
    categoria: 'Obra Publica',
    descripcion: 'Trabajos de conservacion periodica incluyendo recarpeteo, bacheo profundo y senalizacion de la carretera Transpeninsular del km 0 al km 220 en Baja California Sur.',
    entidad_federativa: 'Baja California Sur',
    unidad_compradora: 'Centro SCT Baja California Sur',
    numero_expediente: 'E19/2026',
    fecha_limite_aclaraciones: '2026-04-10T10:00:00Z',
  },
  {
    numero_procedimiento: 'AD-011000001-E17-2026',
    titulo: 'Impresion y distribucion de libros de texto gratuitos ciclo 2026-2027',
    dependencia: 'Secretaria de Educacion Publica',
    tipo_procedimiento: 'Adjudicacion Directa',
    fecha_publicacion: '2026-03-16T10:00:00Z',
    fecha_apertura: '2026-04-02T10:00:00Z',
    monto_estimado: 1_500_000_000,
    estado: 'Adjudicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2637122',
    categoria: 'Educacion',
    descripcion: 'Servicio integral de impresion, encuadernacion y distribucion de libros de texto gratuitos para educacion basica del ciclo escolar 2026-2027 a nivel nacional.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Comision Nacional de Libros de Texto Gratuitos',
    numero_expediente: 'E17/2026',
    fecha_limite_aclaraciones: '2026-03-25T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-016B00001-E23-2026',
    titulo: 'Rehabilitacion de plantas de tratamiento de aguas residuales en el Valle de Mexico',
    dependencia: 'Comision Nacional del Agua',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-28T08:00:00Z',
    fecha_apertura: '2026-04-29T10:00:00Z',
    monto_estimado: 650_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2637223',
    categoria: 'Medio Ambiente',
    descripcion: 'Rehabilitacion y modernizacion de 5 plantas de tratamiento de aguas residuales en el Valle de Mexico para incrementar su capacidad de procesamiento.',
    entidad_federativa: 'Estado de Mexico',
    unidad_compradora: 'Organismo de Cuenca Aguas del Valle de Mexico',
    numero_expediente: 'E23/2026',
    fecha_limite_aclaraciones: '2026-04-17T10:00:00Z',
  },
  {
    numero_procedimiento: 'IA-016000001-E24-2026',
    titulo: 'Estudio de impacto ambiental para el proyecto del Tren Interocenico',
    dependencia: 'Secretaria de Medio Ambiente y Recursos Naturales',
    tipo_procedimiento: 'Invitacion a cuando menos 3',
    fecha_publicacion: '2026-03-25T10:00:00Z',
    fecha_apertura: '2026-04-11T10:00:00Z',
    monto_estimado: 18_000_000,
    estado: 'En evaluacion',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2637324',
    categoria: 'Medio Ambiente',
    descripcion: 'Elaboracion del Manifiesto de Impacto Ambiental modalidad regional para el proyecto del Tren Interocenico del Istmo de Tehuantepec, tramo Coatzacoalcos-Salina Cruz.',
    entidad_federativa: 'Oaxaca',
    unidad_compradora: 'Direccion General de Impacto y Riesgo Ambiental',
    numero_expediente: 'E24/2026',
    fecha_limite_aclaraciones: '2026-04-03T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-051GYN001-E25-2026',
    titulo: 'Servicio de alimentacion para hospitales y clinicas del ISSSTE a nivel nacional',
    dependencia: 'Instituto de Seguridad y Servicios Sociales de los Trabajadores del Estado',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-22T08:00:00Z',
    fecha_apertura: '2026-04-23T10:00:00Z',
    monto_estimado: 420_000_000,
    estado: 'En periodo de aclaraciones',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2637425',
    categoria: 'Salud',
    descripcion: 'Servicio integral de alimentacion (preparacion, distribucion y servicio) para pacientes hospitalizados y personal de guardia en hospitales del ISSSTE.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Subdireccion de Abastecimiento y Servicios',
    numero_expediente: 'E25/2026',
    fecha_limite_aclaraciones: '2026-04-12T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-006HHG001-E26-2026',
    titulo: 'Construccion de linea de transmision electrica de 400 kV Oaxaca-Guerrero',
    dependencia: 'Comision Federal de Electricidad',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-19T10:00:00Z',
    fecha_apertura: '2026-04-19T14:00:00Z',
    monto_estimado: 5_600_000_000,
    estado: 'Presentacion de propuestas',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2637526',
    categoria: 'Energia',
    descripcion: 'Construccion de linea de transmision electrica de 400 kV en doble circuito del tramo Oaxaca-Guerrero con una longitud aproximada de 285 km.',
    entidad_federativa: 'Oaxaca',
    unidad_compradora: 'Subdireccion de Transmision',
    numero_expediente: 'E26/2026',
    fecha_limite_aclaraciones: '2026-04-08T11:00:00Z',
  },
  {
    numero_procedimiento: 'AD-019GYR040-E27-2026',
    titulo: 'Servicio de dialisis peritoneal domiciliaria para derechohabientes del IMSS',
    dependencia: 'Instituto Mexicano del Seguro Social',
    tipo_procedimiento: 'Adjudicacion Directa',
    fecha_publicacion: '2026-03-30T08:00:00Z',
    fecha_apertura: '2026-04-06T10:00:00Z',
    monto_estimado: 8_500_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2637627',
    categoria: 'Salud',
    descripcion: 'Contratacion del servicio integral de dialisis peritoneal automatizada domiciliaria incluyendo equipo, insumos y capacitacion para pacientes del IMSS.',
    entidad_federativa: 'Jalisco',
    unidad_compradora: 'Delegacion Estatal Jalisco',
    numero_expediente: 'E27/2026',
    fecha_limite_aclaraciones: '2026-04-03T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-018TOQ001-E28-2026',
    titulo: 'Perforacion de pozos exploratorios en aguas someras del Golfo de Mexico',
    dependencia: 'Petroleos Mexicanos',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-13T09:00:00Z',
    fecha_apertura: '2026-04-13T11:00:00Z',
    monto_estimado: 8_500_000_000,
    estado: 'En evaluacion',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2637728',
    categoria: 'Energia',
    descripcion: 'Servicio integral de perforacion de 12 pozos exploratorios en aguas someras del Golfo de Mexico, incluyendo equipo de perforacion, lodos y cementacion.',
    entidad_federativa: 'Campeche',
    unidad_compradora: 'Gerencia de Contrataciones para Exploracion y Produccion',
    numero_expediente: 'E28/2026',
    fecha_limite_aclaraciones: '2026-04-01T10:00:00Z',
  },
  {
    numero_procedimiento: 'IA-007000999-E29-2026',
    titulo: 'Adquisicion de raciones de combate tipo 24 horas para operaciones militares',
    dependencia: 'Secretaria de la Defensa Nacional',
    tipo_procedimiento: 'Invitacion a cuando menos 3',
    fecha_publicacion: '2026-03-27T08:00:00Z',
    fecha_apertura: '2026-04-12T10:00:00Z',
    monto_estimado: 145_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2637829',
    categoria: 'Defensa',
    descripcion: 'Adquisicion de raciones de combate individuales tipo 24 horas con valor nutricional especifico para operaciones militares de campo.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Direccion General de Administracion',
    numero_expediente: 'E29/2026',
    fecha_limite_aclaraciones: '2026-04-05T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-006000998-E30-2026',
    titulo: 'Servicio de mesa de ayuda y soporte tecnico de primer y segundo nivel para el SAT',
    dependencia: 'Servicio de Administracion Tributaria',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-31T10:00:00Z',
    fecha_apertura: '2026-05-02T14:00:00Z',
    monto_estimado: 52_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2637930',
    categoria: 'Tecnologias de la Informacion',
    descripcion: 'Servicio de mesa de ayuda (Service Desk) y soporte tecnico de primer y segundo nivel para los usuarios de los sistemas y equipos de computo del SAT a nivel nacional.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Administracion General de Comunicaciones y Tecnologias de la Informacion',
    numero_expediente: 'E30/2026',
    fecha_limite_aclaraciones: '2026-04-20T11:00:00Z',
  },
  {
    numero_procedimiento: 'LA-050GYR001-E31-2026',
    titulo: 'Adquisicion de ambulancias equipadas tipo II y tipo III para el IMSS',
    dependencia: 'Instituto Mexicano del Seguro Social',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-24T08:00:00Z',
    fecha_apertura: '2026-04-24T10:00:00Z',
    monto_estimado: 340_000_000,
    estado: 'En periodo de aclaraciones',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2638031',
    categoria: 'Salud',
    descripcion: 'Adquisicion de 120 ambulancias equipadas, 80 tipo II (soporte basico) y 40 tipo III (soporte avanzado de vida), para unidades medicas del IMSS a nivel nacional.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Coordinacion de Adquisicion de Bienes y Contratacion de Servicios',
    numero_expediente: 'E31/2026',
    fecha_limite_aclaraciones: '2026-04-13T10:00:00Z',
  },
  {
    numero_procedimiento: 'AD-016B00001-E32-2026',
    titulo: 'Servicio de pronostico meteorologico especializado para cuencas hidrologicas',
    dependencia: 'Comision Nacional del Agua',
    tipo_procedimiento: 'Adjudicacion Directa',
    fecha_publicacion: '2026-03-29T08:00:00Z',
    fecha_apertura: '2026-04-07T10:00:00Z',
    monto_estimado: 4_200_000,
    estado: 'Adjudicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2638132',
    categoria: 'Medio Ambiente',
    descripcion: 'Servicio especializado de pronostico meteorologico e hidrologico para las principales cuencas del pais con fines de prevencion de inundaciones y gestion de presas.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Subdireccion General Tecnica',
    numero_expediente: 'E32/2026',
    fecha_limite_aclaraciones: '2026-04-03T10:00:00Z',
  },
  {
    numero_procedimiento: 'LA-011000001-E33-2026',
    titulo: 'Equipamiento de aulas digitales para escuelas de educacion basica',
    dependencia: 'Secretaria de Educacion Publica',
    tipo_procedimiento: 'Licitacion Publica',
    fecha_publicacion: '2026-03-27T10:00:00Z',
    fecha_apertura: '2026-04-27T14:00:00Z',
    monto_estimado: 230_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2638233',
    categoria: 'Educacion',
    descripcion: 'Adquisicion e instalacion de equipamiento tecnologico para 5,000 aulas digitales en escuelas de educacion basica, incluyendo pizarrones interactivos, computadoras y conectividad.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Direccion General de Tecnologias de la Informacion y Comunicaciones',
    numero_expediente: 'E33/2026',
    fecha_limite_aclaraciones: '2026-04-16T11:00:00Z',
  },
  {
    numero_procedimiento: 'IA-027000001-E34-2026',
    titulo: 'Auditoria externa al sistema CompraNet version 6.0',
    dependencia: 'Secretaria de la Funcion Publica',
    tipo_procedimiento: 'Invitacion a cuando menos 3',
    fecha_publicacion: '2026-03-31T10:00:00Z',
    fecha_apertura: '2026-04-15T10:00:00Z',
    monto_estimado: 12_000_000,
    estado: 'Publicada',
    url_compranet: 'https://compranet.hacienda.gob.mx/esop/guest/go/opportunity/detail?opportunityId=2638334',
    categoria: 'Consultoria',
    descripcion: 'Servicio de auditoria externa de seguridad informatica, desempeno y funcionalidad del sistema CompraNet version 6.0 incluyendo pruebas de penetracion.',
    entidad_federativa: 'Ciudad de Mexico',
    unidad_compradora: 'Unidad de Gobierno Digital',
    numero_expediente: 'E34/2026',
    fecha_limite_aclaraciones: '2026-04-08T10:00:00Z',
  },
]
